### ISSUE TITLE
Standalone links dead

### ISSUE THREAD

**Issue by endless22** [dyu/bookmarks#1]
Hello,

The standalone link for the quickstart seems to be dead.
[https://unpkg.com/dyu-bookmarks@0.4.1/bin/bookmarks-linux-standalone-x64.tar.gz](https://unpkg.com/dyu-bookmarks@0.4.1/bin/bookmarks-linux-standalone-x64.tar.gz)
Can you please fix it 🙏.

Thanks.

**Comment by dyu** [comment]
Thanks.  It seems to be a cloudflare issue on their end.
Can you try the link below and see if it works for you?
https://cdn.jsdelivr.net/npm/dyu-bookmarks@0.4.1/bin/bookmarks-linux-standalone-x64.tar.gz

**Comment by dyu** [comment]
Fixed the links
